before_script:
  - export OSS_BUILD_REF_BRANCH="develop"
  - export OSS_BUILD_CONFIG_REF_BRANCH="develop"
#  - export OSS_BUILD_GIT_SERVICE="https://github.com"
#  - export OSS_BUILD_GIT_REPO_OWNER="home1-oss"

stages:
- test_and_build
- deploy

on_every_push:
  stage: test_and_build
  script:
  - echo "on_every_push"
  - bash ci.sh test_and_build
  artifacts:
    expire_in: 1 day
    untracked: true

on_develop_push:
  stage: deploy
  script:
  - echo "on_develop_push"
  - bash ci.sh publish_snapshot
  - bash ci.sh publish_maven_site
  only:
  - develop
  dependencies:
  - on_every_push

on_master_push:
  stage: deploy
  script:
  - echo "on_master_push"
  - bash ci.sh publish_release
  - bash ci.sh publish_maven_site
  only:
  - master
  dependencies:
  - on_every_push

on_release_tag:
  stage: deploy
  script:
  - echo "on_release_tag"
  - bash ci.sh publish_release_tag
  only:
  - /^release.+$/

