#before_script:
#- export VARIABLE_NAME="value"

stages:
- test_and_build
- deploy

on_every_push:
  artifacts:
    expire_in: 1 day
    untracked: true
  script:
  - echo "on_every_push"
  - bash ci.sh test_and_build
  stage: test_and_build

on_develop_push:
  dependencies:
  - on_every_push
  only:
  - develop
  script:
  - echo "on_develop_push"
  - bash ci.sh publish_snapshot publish_maven_site
  stage: deploy

on_master_push:
  dependencies:
  - on_every_push
  only:
  - master
  script:
  - echo "on_master_push"
  - bash ci.sh publish_release publish_maven_site
  stage: deploy

on_release_tag:
  only:
  - /^release.+$/
  script:
  - echo "on_release_tag"
  - bash ci.sh publish_release_tag
  stage: deploy
