
#before_install:
#  - wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
#  - unzip -qq apache-maven-3.3.9-bin.zip
#  - export M2_HOME=$PWD/apache-maven-3.3.9
#  - export PATH=$M2_HOME/bin:$PATH

branches:
  only:
  - master
  - develop
  - build_on_trivasci

cache:
  directories:
  - $HOME/.m2
  - $HOME/.cache
  - '$HOME/.sonar/cache'

env:
  # adapt with gitlab-ci
  - CI_BUILD_REF_NAME=$TRAVIS_BRANCH
  - GIT_SERVICE=https://github.com
  - INFRASTRUCTURE=github

jdk:
  - oraclejdk8

language: java

# not working
#maven:
#  version: 3.3.9

script:
  - echo "on_every_push"
  - bash ci.sh test_and_build

